# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

- script: |
    setx TYPESPEC_VSCODE_TELEMETRY_KEY "20698735-a180-4374-add0-9fba474f66c0"
    echo %TYPESPEC_VSCODE_TELEMETRY_KEY%
  displayName: 'environment variable setup'

- script: |
    echo %TYPESPEC_VSCODE_TELEMETRY_KEY%
  displayName: 'display variable'
